name: moneyloaner

services:
  localhost.sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: moneyloaner_sql
    environment:
      SA_PASSWORD: "2LB%sL!fq%XNQ6&#cGG"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - moneyloaner-net

  localhost.api:
    build:
      context: .
      dockerfile: MoneyLoaner.Api/Dockerfile
    container_name: moneyloaner_api
    ports:
      - "8080:80"
    depends_on:
      - localhost.sql
    networks:
      - moneyloaner-net
    environment:
      - RanInDocker=true
      
  localhost.appserver:
    build:
      context: .
      dockerfile: MoneyLoaner.App/Dockerfile
    container_name: moneyloaner_app
    ports:
      - "8081:80"
    depends_on:
      - localhost.api
    networks:
      - moneyloaner-net
    environment:
      - RanInDocker=true

networks:
  moneyloaner-net:
    driver: bridge